### ISSUE TITLE
SC_03 - As a developer, I want a prototyping PCB that demonstrates all the functionalities of the Cabinet PCB

### ISSUE THREAD

**Issue by Bart2000** [Bart2000/StackCabinet#3]
**DoD**
Making 3 individual prototyping PCBs to test all the complex hardware before making a final order.

- [x] Controls to actuate the solenoid
- [x] Switching regulator to step down the voltage to 24V and 5V
- [x] Transistor array for controlling the 12 LEDs

**Comment by Krakert** [comment]
**ATtiny**
* ATtiny1616-SFR

**LED**
* ASMB-MTB0-0B3A2

**Step Down converter** 
* **Step-Down Voltage Regulator 48V -> 24V @ 1A (solenoid)**
   -  LM2576HVT - ADJ
   - **ARG05FTC2701** -> 2.7k resistor for LM2576HVT feedback voltage divider
   - **ARG05DTC5002** -> 50k resistor for LM2576HVT feedback voltage divider
   - **DSK26** -> 60V, 2A catch diode for LM2576HVT 
   - **LV101M063G105ETR** -> 100uF, 63V electrolytic capacitor for output decoupling of LM2576HVT 
   - **YPRH1508-331M** -> 330uH inductor for LM2576HVT 
* **Step-Down Voltage Regulator 24V -> 5V @ 1A (main electronic)** 
(High voltage (> 40V) Step-Down Regulator are not commonly available, that's why we will transform the 24V to 5V)
   - XL1509-5.0E1
   - **ACPR1208S680MT** -> 68uH inductor for XL1509-5.0E1
   - **LKMD0901V181MF** -> 180uF, 35V electrolytic capacitor for output decoupling of XL1509-5.0E1
   - **ECR1VGK471MFA100016** ->470uF, 35V electrolytic capacitor for input decoupling of XL1509-5.0E1

**Miscellaneous**
* **AR05CTC1000** -> 1k resistor for transistors
* **SI2308A** -> MOSFET for solenoid
@Bart2000 Would use the AO3400A, a cheaper and higher performing (lower RDS(ON)), for the LED would I think a standard transistor is a better option? For low current,  RDS(ON)) is very high.

**Comment by Krakert** [comment]
**BOM**
| Ref                                | Value             | LCSC     | Qty |
|------------------------------------|-------------------|----------|-----|
| C1                                 | 100 uF 63V        | C713372  | 1   |
| C2, C3                             | 470uF 35V         | C397095  | 2   |
| C4                                 | 100 uF 16V        | C43803   | 1   |
| C5                                 | 100nF 50V         | C1711    | 1   |
| C6                                 | 10uF 10V          | C17024   | 1   |
| D3-D6                              | LED RGB           | Farnell  | 4   |
| D1, D2, D7                         | DSK26             | C3015222 | 3   |
| J1-J4                              | Conn_01x08_Female | C691120  | 4   |
| J1-J4                              | Conn_01x08_male   | C2935948 | 4   |
| J5                                 | Screw terminal    | C918120  | 1   |
| L1                                 | 1.8A 330uH        | C970548  | 1   |
| L2                                 | 400mA 47uH        | C2929422 | 1   |
| Q1-Q3                              | BC817             | C52801   | 3   |
| Q4                                 | AO3400A           | C347475  | 1   |
| Q5-Q8                              | BC857             | C8666    | 4   |
| R1                                 | 2k7               | C218493  | 1   |
| R2                                 | 50k               | C2828840 | 1   |
| R4, R7, R11, R14                   | 120               | C25280   | 4   |
| R5, R6, R8, R9, R12, R13, R15, R16 | 100               | C17414   | 8   |
| R3, R10, R17-R22                   | 10K               | C17414   | 8   |
| SW1                                | SW_DIP_x01        | C115371  | 1   |
| U1                                 | LM2576HVS-ADJ     | C126041  | 1   |
| U2                                 | XL1509-5.0        | C61063   | 1   |
